# Generated by Django 5.0.1 on 2024-01-12 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_task_customer_last_name_alter_customer_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='name',
        ),
    ]
