# Generated by Django 5.0.1 on 2024-01-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_title_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='number',
            field=models.CharField(default='One', max_length=50),
        ),
    ]
